<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }

    public  function getLoggidinUsers($intUserId,$date)
    {        
        $query =  $this->createQuery('p')
        ->select('*')
        ->where('is_online=?','Y')
        ->andwhere('user_id!=?',$intUserId)
        ->andWhere('last_activity >=?',$date)
        ->execute();

        return $query->toArray();
    }

    public function getchatdatabyuser($username,$intrecd){
        $query =  $this->createQuery()
                ->select('*')
                ->from('Chat')
                ->where('to_user=?',$username)
                ->andwhere('recd=?',$intrecd)
                ->execute()->toArray();
        return $query;

    }

    public function updatechatbox($username,$intrecd,$newintrecd){
        $query =  $this->createQuery()
                ->update('Chat')
                ->set('recd','?',$newintrecd)
                ->where('to_user=?',$username)
                ->andwhere('recd=?',$intrecd)
                ->execute();
        return $query;
    }

    public function savechat($from,$to,$message,$sent){
        $obj = new Chat();
        $obj->setFromUser($from);
        $obj->setToUser($to);
        $obj->setMessage($message);
        $obj->setSent($sent);
        $obj->save();
    }

    public function saveuser($intUserId,$strUserName,$boolOnline,$date){
        $obj = new User();
        $obj->setUserId($intUserId);
        $obj->setUserName($strUserName);
        $obj->setIsOnline($boolOnline);
        $obj->setLastActivity($date);
        $obj->save();
    }

    public function updateUser($intUserId,$strUserName,$boolStatus){
        $query =  $this->createQuery()
                ->update('User')
                ->set('is_online','?',$boolStatus)
                ->set('last_activity','?',date('Y-m-d H:i:s'))
                ->where('user_id=?',$intUserId)
                ->andwhere('user_name=?',$strUserName)
                ->execute();
        return $query;
    }

    public function checkUserChat($intUserId){
        $query =  $this->createQuery()
                ->select('*')
                ->from('User')
                ->where('user_id=?',$intUserId)
                ->execute()->toArray();
        return $query;
    }

    public function updatechatlastactivity($strUserName,$intUserId,$boolStatus){
        $query =  $this->createQuery()
                ->update('User')
                ->set('last_activity','?',date('Y-m-d H:i:s'))
                ->where('user_id=?',$intUserId)
                ->andwhere('user_name=?',$strUserName)
                ->execute();
        return $query;
    }

    
}